fixed cause of AttributeError in callback
on line ``39``, 
```python
l.append(v.item())
```
gives the error:
> AttributeError: 'float' object has no attribute 'item'

changing to ``l.append(v)`` fixed this